package com.grgr.dto;

/*
CREATE TABLE FREE_LIKE(FREE_LIKE_NO NUMBER PRIMARY KEY
		, UNO NUMBER, CONSTRAINT FREE_LIKE_UNO_FK FOREIGN KEY(UNO) REFERENCES USERINFO(UNO)
		, FREE_BNO NUMBER, CONSTRAINT FREE_LIKE_BNO_FK FOREIGN KEY(FREE_BNO) REFERENCES FREE_BOARD(FREE_BNO)
		, FREE_LIKE_REGDATE DATE DEFAULT SYSDATE);
		
CREATE SEQUENCE FREE_LIKE_SEQ;		
*/






public class FreeLike {
	int freeLikeNo;
	int uno;
	int freeBno;
	int freeLikeRegdate;
	
	
	
	
	
	
}
