package com.grgr.dto;

import lombok.Data;

/*
CREATE TABLE INFO_LIKE(
INFO_LIKE_NO NUMBER PRIMARY KEY,
UNO NUMBER, CONSTRAINT INFO_LIKE_UNO_FK FOREIGN KEY(UNO) REFERENCES USERINFO(UNO),
INFO_BNO NUMBER , CONSTRAINT INFO_LIKE_BNO_FK FOREIGN KEY(INFO_BNO) REFERENCES INFO_BOARD(INFO_BNO),
INFO_LIKE_REGDATE DATE DEFAULT SYSDATE
);

 CREATE SEQUENCE INFO_LIKE_SEQ;
 

 */

@Data
public class InfoLike {
	int infoLikeNo;
	int uno;
	int infoBno;
	int infoLikeRegdate;

}
